title: Introduccion a HTML
description: If you are looking for a quick and fun introduction to the exciting world of programming, this course is for you. Learn fundamental HTML skills and build your first webpage in less than an hour.
template:
  name: intro-html
  repo: intro-html-plantilla
  description: "A robot powered training repository :robot:"
before:
  - type: createIssue
    title: Bienvenida
    body: 01-welcome.md
  - type: updateBranchProtection

steps:
  - title: Activa GitHub Pages
    description: Activa GitHub Pages en la página de ajustes de este repositorio.
    event: page_build
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: octokit
        method: repos.getPages
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: pagesUrl
      - type: respond
        with: 00-openapr.md
        data:
          pagesUrl: "%actions.pagesUrl.data.html_url%"
        issue: Welcome

  - title: Abre una solicitud de extracción
    description: Abre una solicitud de extracción.
    event: pull_request.opened
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: ===
        right: add-index
      - type: gate
        left: "%payload.pull_request.base.ref%"
        operator: ===
        right: master
      - type: closeIssue
        issue: Bienvenida
        action_id: prev
        required: false
      - type: createPullRequestComment
        body: 02-html-structure.md
        file: index.html
        position: 1
        data:
          welcomeLink: "%actions.prev.data.html_url%"

  - title: Crea la estructura del documento HTML
    description: Sigue las instrucciones para escribir la estructura base de tu archivo HTML.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: html
        action_id: contains_html
        required: false
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: body
        action_id: contains_body
        required: false
      - type: gate
        every: true
        gates:
          - left: "%actions.contains_html%"
          - left: "%actions.contains_body%"
        else:
          type: createReview
          body: 03e-add-html.md
          event: REQUEST_CHANGES
      - type: createPullRequestComment
        body: 03-title-tag.md
        file: index.html
        position: 2

  - title: Añade una etiqueta de título
    description: Añade una etiqueta de título.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: head
        action_id: contains_head
        required: false
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: title
        action_id: contains_title
        required: false
      - type: gate
        every: true
        gates:
          - left: "%actions.contains_title%"
          - left: "%actions.contains_head%"
        else:
          type: createReview
          event: REQUEST_CHANGES
          body: 03e-add-title.md
      - type: createReview
        event: APPROVE
        body: 04-merge-first-pr.md

  - title: Fusiona tu primera solicitud de extracción
    description: Fusiona tu solicitud de extracción.
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: octokit
        method: repos.getPages
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: pagesUrl
      - type: createIssue
        title: Añade un encabezado
        body: 05-h1-tag.md
        data:
          pagesUrl: "%actions.pagesUrl.data.html_url%"
        action_id: new_issue
      - type: respond
        with: next.md
        data:
          issueURL: "%actions.new_issue.data.html_url%"

  - title: Cambia tu nombre de usuario a una etiqueta h1
    description: Cambia tu nombre de usuario a una etiqueta h1.
    event: pull_request
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: synchronize
      - type: gate
        left: "%payload.pull_request.base.ref%"
        operator: ===
        right: master
      - type: gate
        left: "%payload.action%"
        operator: "!=="
        right: opened
        required: false
        else:
          type: closeIssue
          issue: Añade un encabezado
          required: false
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: h1
        action_id: contains_h1
        required: false
      - type: gate
        left: "%actions.contains_h1%"
        else:
          type: createReview
          event: REQUEST_CHANGES
          body: 05e-troubleshoot-h1.md
      - type: createPullRequestComment
        body: 06-add-image.md
        file: index.html
        position: 5

  - title: Añade una imagen
    description: Añade una imagen.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: img
        attribute: src
        action_id: contains_img
      - type: gate
        left: "%actions.contains_img%"
        else:
          type: createReview
          body: 06e-image.md
          event: REQUEST_CHANGES
      - type: createReview
        body: 07-merge-second-pr.md
        event: APPROVE

  - title: Fusiona tu segunda solicitud de extracción
    description: Fusiona tu solicitud de extracción
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: octokit
        method: repos.getPages
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: pagesUrl
      - type: createIssue
        action_id: new_issue
        title: Create a list
        body: 08-create-list.md
        data:
          pagesUrl: "%actions.pagesUrl.data.html_url%"
      - type: respond
        with: next.md
        data:
          issueURL: "%actions.new_issue.data.html_url%"

  - title: Crea una lista
    description: Crea una lista.
    event: pull_request
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: synchronize
      - type: gate
        left: "%payload.pull_request.base.ref%"
        operator: ===
        right: master
      - type: gate
        left: "%payload.action%"
        operator: "!=="
        right: opened
        required: false
        else:
          type: closeIssue
          issue: Crea una lista
          required: false
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: ul
        action_id: contains_ul
        required: false
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: ol
        action_id: contains_ol
        required: false
      - type: gate
        gates:
          - left: "%actions.contains_ul%"
          - left: "%actions.contains_ol%"
        else:
          type: createReview
          body: 08e-list.md
          event: REQUEST_CHANGES
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: li
        action_id: contains_li
        required: false
      - type: gate
        gates:
          - left: "%actions.contains_li%"
        else:
          type: createReview
          body: 08e-list.md
          event: REQUEST_CHANGES
      - type: createPullRequestComment
        body: 09-add-links.md
        file: index.html
        position: 7

  - title: Añade enlaces
    description: Añade enlaces.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: "%actions.index_file%"
        tag: a
        action_id: contains_a
        required: false
      - type: gate
        left: "%actions.contains_a%"
        else:
          type: createReview
          body: 09e-links.md
          event: REQUEST_CHANGES
      - type: createReview
        body: 10-merge-third-pr.md
        event: APPROVE

  - title: Fusiona tu tercera solicitud de extracción
    description: Fusiona tu solicitud de extracción.
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: mergeBranch
        head: master
        base: add-style
      - type: createPullRequest
        title: Añade un poco de estilo a tu página
        head: add-style
        body: 11-link-css.md
        action_id: new_pr
      - type: respond
        with: next.md
        data:
          issueURL: "%actions.new_pr.data.html_url%"

  - title: Hazlo bonito
    description: Añade algunos estilos a tu nuevo sitio
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index
      - type: gate
        left: '/<link rel="stylesheet" href="style.css">/'
        operator: test
        right: "%actions.index%"
        else:
          type: respond
          with: 11-style-fail.md
      - type: removeBranchProtection
      - type: respond
        with: 11-style-success.md

  - title: Fusiona la última solicitud de extracción
    description: Prepárate para mostrar al mundo tus nuevas capacidades.
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: octokit
        method: repos.getPages
        owner: "%payload.repository.owner.login%"
        repo: "%payload.repository.name%"
        action_id: pagesUrl
      - type: respond
        with: 12-big-finish.md
        data:
          pagesUrl: "%actions.pagesUrl.data.html_url%"

tags:
  - GitHub Pages
